### PR TITLE
51 move bet handling to backend

### PR DESCRIPTION
**Pull request by EmuMan**

### CODE REVIEW

**Review by 1colinmcdonald — CHANGES_REQUESTED** [review]
It doesn't seem like betting works.

I realized that it's because I ran out of points.

**Review by 1colinmcdonald — APPROVED** [review]
Looks good

**Review by svenlinus — APPROVED** [review]
Looks good

**Review by Gabe-Alonso — APPROVED** [review]
Looks great, bestie, good work.

**Review by Thundderr — APPROVED** [review]
Code all looks good, works on my end.

**Pull request merged**
